apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      tier: db
  template:
    metadata:
      labels:
        app: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379