apiVersion: v1
kind: Service
metadata:
  name: my-tornado
  labels:
    run: my-tornado
spec:
  type: NodePort
  ports:
  - nodePort: 30007
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: tornado